---

#################################
#
# 下载新jar包
#
#################################

- name: delete old jar
  shell: rm -f /app/appuser/{{ jar_pre }}*.jar

- name: download new jar
  get_url:
    url: "{{ jar_url }}"
    backup: yes
    dest: /app/appuser
    username: "{{ dowload_username }}"
    password: "{{ dowload_password }}"

# - name: check jar exist
#   shell: ls {{ deploy_path }}/{{ jar_name }}
#   register: jar_exist

# - name: jar is exist
#   debug: var=jar_exist

- name: check jar exist
  include: ../../check_jar_exist/tasks/check_jar_exist.yml