server:
  port: 8544


createJarTime: '@build.time@'

nacos:
  config:
    server-addr: 127.0.0.1:8849
  discovery:
    server-addr: 127.0.0.1:8849

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8544
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: SampleSite