server:
  port: 8544

#打包时间
createJarTime: '@build.time@'

#nacos配置中心及注册中心
nacos:
  config:
    server-addr: 127.0.0.1:8848
    username: nacos
    password: nacos
    auto-refresh: true
  discovery:
    server-addr: 127.0.0.1:8848
    auto-register: false
    username: nacos
    password: nacos

#服务健康性检查
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8544
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: SampleSite
  rabbitmq:
    host: 82.157.129.159
    port: 5672
    username: root
    password: 123456