---

#####################
#
# 检查jar包是否存在
#
#####################

- name: check jar exist
  shell: ls {{ deploy_path }}/{{ jar_name }}
  register: jar_exist
  ignore_errors: true

- name: jar is exist
  debug: var=jar_exist