---

######################
#
# 升级失败回滚
#
######################

- name: rollback jar
  include: rollback.yml
  # when: launch_result is failure or jar_exist is failure or check_port_result is failure or http_api_result is failure or http_api_result != 200